"""add embeddings to document chunks

Revision ID: df0b8bf222d4
Revises: e53925b6cf26
Create Date: 2026-09-30 13:11:13.338023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = 'df0b8bf222d4'
down_revision: Union[str, Sequence[str], None] = 'e53925b6cf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'document_chunks',
    sa.Column('embedding', VECTOR(dim=384), nullable=True)
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
